[env:esp32-devkitc-v4]
platform = espressif32
board = esp32-devkitc-v4
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
    WiFi
    SPIFFS

build_flags =
    -DCORE_DEBUG_LEVEL=3

[platformio]
default_envs = esp32-devkitc-v4